- src/components/FavoritesList.svelte
- src/components/PlayingPreview.svelte
- src/components/Results.svelte
Now truncated music titles will show the whole title on hover (implemented using the `title` attribute)
> Refinements: music title truncate

- src/components/Results.svelte
When an artist name is longer than the music name, love icon is incorrectly positioned.
This pull aims to fix this issue.
Before:
After:
> fix: love search icon positioning

- src/components/Results.svelte
Love icon on search was "blocking" panel switch (ex. from search to favorites) to execute transition.
Solution: usage of `local` transition.
> fix: love search animation timing

- src/components/Settings.svelte
- src/lib/ActionButton.svelte
Improving settings behavior with these changes:
- import button will warn old favorites will be lost if new ones imported (only showing if there are already favorites present)
- export button will be disabled if there is no favorite to be exported
> settings: improve import-export behavior

- src/components/Player.svelte
- src/components/Toolbar.svelte
Added the "webkit" backdrop-filter property to correctly handle backdrop-filter on Safari.
> fix: backdrop-filter (css) not working on Safari

- src/components/Toolbar/Toolbar.svelte
This change resolves an issue where:
- editing the toolbar was throwing an error on hmr update
- each hmr update could spawn more window event listener that were not removed on destroy: solved by using the `svelte:window` element instead of relating on a "classic" event listener
> fix: toolbar error on hmr update

- src/lib/Modal.svelte
The PlayNext feature (#81) was causing a content overflow when adding many songs.
Fixed this issue by setting a `max-width` and adding `overflow-y: auto` to Modal, allowing it to show a scrollbar when the content needed can't fit the screen size.
---
Before:
After:
> fix: PlayNext scrolling overflow

- src/App.svelte
- src/components/AlbumView.svelte
- src/components/FavoritesView/FavoritesItem.svelte
- src/components/MainLayout.svelte
- src/components/PlayNextView/PlayNextItem.svelte
- src/components/ResultsView/AlbumResultsItem.svelte
- src/components/ResultsView/Results.svelte
- src/components/ResultsView/ResultsItem.svelte
- src/components/Toolbar/Toolbar.svelte
- src/lib/ActionButton.svelte
- src/lib/TextSwitch.svelte
- src/lib/player.ts
- src/lib/resultsGetter.ts
- src/types/Album.ts
- src/types/AlbumResults.ts
This pull implements a new type of search: album search (closes #109).
Because of the amount of work done to support album search, this pull also implements the following changes, code optimizations and fixes:
- 🎨 – new UI element: `TextSwitch` (used to toggle between search modes)
- 🚧 – re-written `Results` component using the built-in Svelte `await`
- 🐛 – fixed general images behavior
- 🚧❗– completely re-written the URL hash behavior as a Svelte store for easily keys read/write on each component (this will keep search query and the selected album also on page reload)
- 🚧❗– completely re-written the window title handling to use the new hash behavior
> feat: album search (+ general code review)

- package-lock.json
- package.json
- src/components/AlbumView.svelte
- src/components/ContextMenu.svelte
- src/components/FavoritesView/FavoritesItem.svelte
- src/components/FavoritesView/FavoritesList.svelte
- src/components/MainLayout.svelte
- src/components/PlayNextView/PlayNextItem.svelte
- src/components/PlayNextView/PlayNextList.svelte
- src/components/PlayNextView/PlayNextView.svelte
- src/components/PlayerControls/PlayerControls.svelte
- src/components/PlayingView/PlayingPoster.svelte
- src/components/ResultsView/AlbumResultsItem.svelte
- src/components/ResultsView/Results.svelte
- src/components/ResultsView/ResultsItem.svelte
- src/components/SWManager.svelte
- src/components/SettingsView/Settings.svelte
- src/components/Toolbar/Autocomplete.svelte
- src/components/Toolbar/Toolbar.svelte
- src/lib/Modal.svelte
- src/lib/audioStreamGetter.ts
- src/lib/player.ts
- src/types/AudioStreamResponse.ts
- src/types/MenuEntry.ts
- src/types/ResultsStatus.ts
This pull includes the following deps updates:
- ❗`svelte` 3.59.2 => 4.0.5
- ❗`vite` 3.2.7 => 4.4.2
- ❗`@sveltejs/vite-plugin-svelte` 1.4.0 => 2.4.2
- `postcss` 8.4.24 => 8.4.25
- `svelte-check` 3.4.4 => 3.4.5
Minor changes are:
- transition modifier: added `global` modifier and removed `local` modifier (to match Svelte 4 new transitions behavior)
- removed `svelte-sortable-list` (unused dependency)
- suppressed `svelte-check` warnings (aria warnings coming with Svelte 4)
- fixed `svelte-check` errors (types couldn't be exported as "default")
> deps: svelte 4 + vite 4 + minor changes

- src/components/FavoritesView/FavoritesItem.svelte
- src/components/PlayNextView/PlayNextController.ts
- src/components/PlayNextView/PlayNextItem.svelte
- src/components/ResultsView/ResultsItem.svelte
- src/lib/audioStreamGetter.ts
- src/types/AudioStreamResponse.ts
This pull makes sure all the audio played is on the best (mp4) available quality. Previously the fist mp4 stream was loaded.
This also solves an [issue](https://twitter.com/GiorgioBellix/status/1643311686768533506) in [Arc Browser](https://arc.net) (Chrome seems not affected) where:
- music quality was degraded
- frequency bars were not working correctly and some frequencies were cut down
> feat: always use best quality audio

- src/components/PlayNextView/PlayNextController.ts
This pull request aims to fix the previous behavior where if the user clicked on a music not in the Play Next list, after playing it, Play Next songs restarted from the beginning.
With these changes, Play Next won't play after a music not in the Play Next list ends and will wait a manual restart from the user.
> fix: prevent Play Next restart after manual play

- src/components/ContextMenu.svelte
- src/components/PlayNextView/PlayNextView.svelte
- src/lib/Modal.svelte
- src/types/MenuEntry.ts
This pull aims to make easier for the user to clear the Play Next list by adding a "Clear Play Next" button on the Play Next list and adding a context menu item to the button for opening Play Next list. Before, the user needed to remove every single item from the list or reload the page.
> feat: ability to clear play next list

- src/components/PlayNextView/PlayNextController.ts
- src/lib/player.ts
This pull fixes an issue caused by #134 where adding a music to Play Next caused it to play immediately, instead of waiting the previous one to end.
This pull also improves the general behavior of Play Next, which becomes so (other than the "normal" behavior):
- if user plays a music and then adds another one to Play Next, the other should wait the first to end
- if user plays another music which is not in Play Next, it should play immediately and Play Next should continue where it left once the user-chosen music has ended, by playing the next song from the song interrupted by the user
- when there is nothing left to play, don't restart from the beginning (this should be manually done by the user)
- if user adds a music after Play Next list was played completely, the user must explicitly …
> fix/feat: better Play Next behavior

- src/lib/AudioPlayer.svelte
- src/lib/audioStreamGetter.ts
- src/lib/player.ts
- src/lib/wantPlay.ts
This pull aims to fix the issue where API fails to retrieve audio but responds without error when getting available streams.
Changes made are:
- added a `failedStreamURLs` store to save APIs that are not working (it resets on page reload)
- stream getter has been converted to a `class`
- APIs inside `failedStreamURLs` are excluded from working APIs and are not used (till page reload)
- the audio played automatically adds APIs not working to `failedStreamURLs` and calls a fallback function on error (it tries to re-fetch excluding the not working API)
- added a new API endpoint: `https://api.piped.projectsegfau.lt`
> fix: mitigate API issues

- src/components/PlayNextView/PlayNextController.ts
- src/components/PlayerControls/PlayerControls.svelte
- src/components/Toolbar/Toolbar.svelte
- src/lib/TextSwitch.svelte
This pull fixes these small issues:
- fix: album list can be replayed on Play Next clear (d906114cbc884e5ce79d88c1f88a7cb0462cb909):\
previously the variables tracking albums and favorites in Play Next didn't reset after clearing the Play Next list, making impossible to replay the list without a page reload
- fix: safari logo position (35e78955c992641513d8163f093071676bfd91eb):\
to fix the incorrectly handled logo size by Safari, `aspect-ratio` was used
- fix: text switch wrong color on safari mobile (5f5e9576f208ac02eb1fd602d7d9e66b94753afa)\
previously the TextSwitch component on Safari Mobile showed a blue (link) color instead of matching the desktop experience (with white color)
- fix: disable toolbar shrink on safari (it lags) (9745d659fc7fdaf2d14a622ad5c53a0987104fb5)
- fix: prevent …
> Small fixes

- src/components/FavoritesView/FavoritesItem.svelte
- src/components/FavoritesView/FavoritesList.svelte
- src/components/PlayNextView/PlayNextItem.svelte
- src/components/PlayNextView/PlayNextList.svelte
- src/components/PlayerControls/PlayerControls.svelte
- src/lib/Orderable.svelte
This pull introduces a new reordering system for favorites and PlayNext list.
The previous system didn't handle properly the user drag movement and didn't handle at all the dropping action between favorites: the action only worked if done on a favorite and the gap between favorites was not handled.
List of changes made in this pull:
- removed old dragging system from `FavoritesItem.svelte`, `FavoritesList.svelte`, `PlayNextItem.svelte` and `PlayNextList.svelte`
- created a new lib component to handle "orderable" (list) items with the new system: `Orderable.svelte`
- used the new dragging system for favorites and Play Next list
- added a `z-index` to the player controls to prevent dragging preview from showing on it
- fixed a wrong padding on `PlayNextList.svelte`, introduced with the new …
> feat: new favorites/playnext reordering system

- src/components/AlbumView.svelte
- src/components/FavoritesView/FavoritesList.svelte
- src/components/PlayNextView/PlayNextView.svelte
- src/lib/Modal.svelte
- src/lib/player.ts
This pull includes the following changes:
- **feat: custom modal scrollbar 4805ebf3004118d5c23d2abcc00582d06f0302fc:** this prevents the scrollbar from not respecting the modal border radius
- **feat: re-shuffle play next 3c2b78e0d17515a5b02e659147971d84dacdd338:** just by clicking a button, all your Play Next can now be re-shuffled
- **feat: always show playing music on play next modal open c227623c8726984dd199105e704bfd5d7e488e8f:** previously the modal always opened on top of the content and the user had to scroll throughout the entire list to find the current playing music
It also includes the following code optimizations:
- **optimization: shuffle as util function 5614e92c57ef10e61a739565f5d97cee4fc65daf**
> feat: play next updates

- src/components/PlayNextView/PlayNextController.ts
- src/components/PlayNextView/PlayNextView.svelte
- src/components/PlayerControls/PlayerControls.svelte
- src/components/SettingsView/Settings.svelte
- src/lib/player.ts
Currently the implementation of Musicale only handles "Next" and "Previous" keyboard buttons, which are keyboard-specific and could not be available to everyone, so "Next" and "Previous" buttons on the player are needed.
This pull implements the following:
- "Next" and "Previous" buttons on the play bar
- Buttons appear only when needed
- An option in settings lets user disable these buttons if wanted
- Buttons appear/disappear (possibly) with an animation
- Buttons become a bit darker (showing they're disabled) when there's no previous/next song to play
- Right click on "Play Next" button allows switching to previous/next song
> feat: previous/next buttons support

- package-lock.json
- package.json
- src/lib/player.ts
This pull removes the "hash" implementation inside Musicale and uses the [svelte-hash](https://github.com/Bellisario/svelte-hash) one.
`svelte-hash` is my new library whose purpose is to extract the original "hash" implementation of Musicale and make it a standalone library for everyone to use.
> feat: use svelte-hash

- src/App.svelte
- src/app.css
- src/components/AlbumView.svelte
- src/components/FavoritesView/FavoritesItem.svelte
- src/components/FavoritesView/FavoritesList.svelte
- src/components/Footer.svelte
- src/components/PlayNextView/PlayNextView.svelte
- src/components/PlayerControls/PlayerControls.svelte
- src/components/ResultsView/AlbumResultsItem.svelte
- src/components/ResultsView/ResultsItem.svelte
- src/components/SettingsView/Settings.svelte
- src/components/Toolbar/Toolbar.svelte
- src/lib/ActionButton.svelte
- src/lib/Modal.svelte
- src/lib/TextSwitch.svelte
- src/lib/focuser/FocusOutline.svelte
- src/lib/focuser/focusable.ts
- src/lib/player.ts
This pull request adds an initial keyboard navigation support, enabling focus outlines on inputs, buttons and links.
While a _browser outline implementation_ is provided (through a settings option), the default settings provides a custom outline implementation that navigates the interface by animating from the focused elements.\
All of this allows custom interaction that can be performed, as an Enter (click) animation when selecting a song to play and a blinking outline when focusing an active element.
---
Changes made are:
- replaced DIVs with native buttons when possible
- enabled _browser outline implementation_ on buttons, inputs and links
- provided a custom implementation that _tweens_ between focusing outlines when changing elements focus
- allowed closing modals with Escape (if …
> feat: initial keyboard navigation

- src/lib/audioStreamGetter.ts
The motivation to do this is because the default instance currently faces a lot of issues.
> Remove default instance when dynamic instances are available
