src/components/FavoritesList.svelte, src/components/Footer.svelte, src/components/MainLayout.svelte, src/components/Results.svelte
Add Copyright, MIT License and GitHub link to all app.
=> Add Copyright and GitHub link

src/components/FavoritesList.svelte
Shuffle algorithm now makes sure:
- musics are not extracted more times before all played once (shuffle ended musics to play);
- last shuffle music is not the the first re-extracted (in a new shuffle).
=> Update: shuffle algorithm

src/components/FavoritesList.svelte, src/components/Toolbar.svelte
This pull makes sure favorites changes are animated and faded.
(Also removes two `Toolbar.svelte` unused imports)
=> Feat: animate favorites list (on favorites change)

src/App.svelte, src/components/Modal.svelte, src/lib/ActionButton.svelte
This pull adds:
- a Modal component
- a warning on mobile usage (built with the new Modal component)
=> feat: Warning modal on mobile

src/App.svelte, src/components/Modal.svelte
When offline, display a modal telling the user to go back online
=> Add offline modal

src/components/Player.svelte
Add a colored time separator for better distinction and theme color usage.
=> feat: colored music time separator

src/assets/love.svg, src/components/Results.svelte
When searching for some music, favorite musics are now displayed with a love icon.
Feature preview:
=> feat: display love icon on favorite search

src/components/Results.svelte, src/components/ResultsItem.svelte
Now you can hover a search result and add or remove it from your favorites.
This improves the old love displaying on search results, which couldn't be toggled.
=> feat: love toggle on search results

index.html
Make analytics script asynchronous to increase performance.
=> feat: async analytics

src/components/Player.svelte
Now the play-pause button has a new YouTube like animation when transitioning between states.
=> UI: change play-pause icon animation

README.md, src/components/Autocomplete.svelte
As said in #41, using Piped API for autocompletion.
=> API: use Piped for search autocompletion

src/components/Autocomplete.svelte, src/components/Toolbar.svelte
Allow controlling autocompletion results with arrow keys (search engine style) for a better user experience and faster searches.
=> feat: allow controlling autocompletion with arrow keys

README.md
=> add: development/running/building instructions on README.md

src/components/FavoritesItem.svelte
This feature allows favorites reordering on personal order.
https://user-images.githubusercontent.com/72039923/222970608-0cb0b7e0-97a7-41ba-995f-7e31667c6b2a.mp4
=> feat: favorites reordering

src/components/Results.svelte, src/lib/resultsGetter.ts
This feature allows loading more results after the initial search.
https://user-images.githubusercontent.com/72039923/223742055-5a8895c6-c4b3-4c39-9bd9-2b010363551d.mp4
=> add: load more results

src/components/ContextMenu.svelte, src/components/FavoritesList.svelte, src/components/MainLayout.svelte, src/components/Modal.svelte, src/components/PlayNext/PlayNextController.ts, src/components/PlayNext/PlayNextItem.svelte, src/components/PlayNext/PlayNextList.svelte, src/components/PlayNext/PlayNextView.svelte, src/components/ResultsItem.svelte, src/lib/player.ts
=> feat: play next beta (#67)

.github/workflows/deploy.yml
This pull updates the following actions of the deploy workflow:
- `actions/checkout`: `v2` => `v3`
- `actions/setup-node`: `v1` => `v3`
=> update: deploy workflow

src/App.svelte, src/components/ResultsView/Results.svelte, src/components/SettingsView/Settings.svelte, src/components/Toolbar/Autocomplete.svelte, src/lib/ActionButton.svelte, src/lib/IntersectionObserver.svelte, src/lib/Modal.svelte, src/lib/Orderable.svelte, src/lib/player.ts, src/lib/resultsGetter.ts, src/main.ts
This pull fixes all the TS errors `svelte-check` was throwing.
=> fix: ts errors

src/lib/audioStreamGetter.ts
Hello, I haven't tested this nor am I familiar with svelte either, but I hope this works in reviving the project.
=> Add support for dynamic instances

src/components/AlbumView.svelte, src/components/Toolbar/Autocomplete.svelte, src/lib/audioStreamGetter.ts, src/lib/resultsGetter.ts, src/lib/store.ts
I'm not sure if it's the right way to globalize the array in svelte but it's a start.
=> feat: use dynamic instances for all endpoints
